apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: default
  labels:
    app: portfolio
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
    - name: http
      port: 80           # ClusterIP port
      targetPort: 80     # Container port
      nodePort: 30080    # Access via http://localhost:30080
      protocol: TCP
